function [centers, radii, count] = countBlueberries(berries)
% this detects circles in an images
[centers, radii, metric] = imfindcircles(berries, [10 29], ...
   'Sensitivity', 0.9400, ...
   'EdgeThreshold', 0.03, ...
   'Method', 'PhaseCode', ...
   'ObjectPolarity', 'Bright');
    % count number 
    count = size(radii,1);

%{
[centers, radii, metric] = imfindcircles(imread(''), [10 29], ...
   'Sensitivity', 0.9400, ...
   'EdgeThreshold', 0.03, ...
   'Method', 'PhaseCode', ...
   'ObjectPolarity', 'Bright');

OR

detectCircles = @(x) imfindcircles(x,[10 29], ...
	'Sensitivity',0.9400, ...
	'EdgeThreshold',0.03, ...
	'Method','PhaseCode', ...
	'ObjectPolarity','Bright');
[centers, radii, metric] = detectCircles(img);
%}
end
